# Generated by Django 6.0.7 on 2026-07-11 09:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rec', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('book', 'Книга'), ('game', 'Игра'), ('fact', 'Интересный факт')], max_length=100, verbose_name='Тип рекомендации')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_rec', models.ImageField(blank=True, null=True, upload_to='recommed_image/', verbose_name='Изображение рекомендации')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe_name', models.CharField(max_length=255, verbose_name='Название настроения')),
                ('image_vibe', models.ImageField(blank=True, null=True, upload_to='image_vibe/', verbose_name='Стикер')),
            ],
            options={
                'verbose_name': 'Настроение',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image_user', models.ImageField(blank=True, null=True, upload_to='diary_photos/', verbose_name='Фото в дневнике')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
            },
        ),
        migrations.CreateModel(
            name='RecommendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_rec', models.CharField(choices=[('favorite', 'Избранное'), ('viewed', 'Просмотрено'), ('disliked', 'Не понравилось')], max_length=100, verbose_name='Статус')),
                ('recommendation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_links', to='moodspace.recommendation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекомендация пользователя',
                'verbose_name_plural': 'Рекомендации пользователя',
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='vibe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendtations', to='moodspace.vibe'),
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
                ('vibe_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_vibe', to='moodspace.vibe')),
            ],
            options={
                'verbose_name': 'Выбранное настроение',
                'verbose_name_plural': 'Выбранные настроения',
            },
        ),
    ]
