# Generated by Django 6.0.7 on 2026-07-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibe',
            name='image_vibe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стикер'),
        ),
    ]
