# Generated by Django 6.0.7 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodspace', '0002_alter_vibe_image_vibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='image_rec',
            field=models.CharField(blank=True, null=True, verbose_name='Изображение рекомендации'),
        ),
    ]
