# Generated by Django 6.0.7 on 2026-07-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodspace', '0003_alter_recommendation_image_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='vibe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='moodspace.vibe'),
        ),
    ]
